spring:
  datasource:
    url: jdbc:mysql://localhost:3306/infuse?useSSL=false&serverTimezone=UTC
    username: <<username>>
    password: <<password>>
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
